name: flutter_google_signin
description: Google signin implementation based on Auth provider.
version: 0.0.1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  auth_provider:
    git:
      url: git@gitlab.com:milind.mevada/dart_auth_provider.git
  google_sign_in: ^4.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
